name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use the desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install numpy pandas  # Add your dependencies here

    - name: Run Tests
      run: |
        chmod +x ./tests.sh
        ./tests.sh

